import React from 'react';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Brain, Zap, Clock, Trophy } from 'lucide-react';

const QuizTopicCard = ({ topic, onStartQuiz, index }) => (
  <motion.div
    initial={{ opacity: 0, scale: 0.9 }}
    animate={{ opacity: 1, scale: 1 }}
    transition={{ delay: index * 0.1 }}
    className="bg-white rounded-xl shadow-lg p-6 hover:shadow-xl transition-all cursor-pointer"
    onClick={() => onStartQuiz(topic)}
  >
    <div className="text-center mb-4">
      <div className="text-4xl mb-3">{topic.icon}</div>
      <h3 className="text-xl font-bold text-gray-900 mb-2">{topic.title}</h3>
      <p className="text-gray-600 text-sm">{topic.description}</p>
    </div>
    <div className="space-y-2 text-sm text-gray-600">
      <div className="flex justify-between">
        <span>Difficulty:</span>
        <span className={`font-semibold ${
          topic.difficulty === 'Beginner' ? 'text-green-600' :
          topic.difficulty === 'Intermediate' ? 'text-yellow-600' : 'text-red-600'
        }`}>{topic.difficulty}</span>
      </div>
      <div className="flex justify-between">
        <span>Questions:</span>
        <span className="font-semibold">{topic.questions}</span>
      </div>
      <div className="flex justify-between">
        <span>Time Limit:</span>
        <span className="font-semibold">{Math.floor(topic.timeLimit / 60)} min</span>
      </div>
    </div>
    <Button className="w-full mt-4 bg-gradient-to-r from-indigo-500 to-purple-600 text-white hover:from-indigo-600 hover:to-purple-700">
      Start Quiz
    </Button>
  </motion.div>
);

const QuizTopicSelection = ({ quizTopics, onStartQuiz, onBack }) => (
  <motion.div
    initial={{ opacity: 0, y: 20 }}
    animate={{ opacity: 1, y: 0 }}
    className="space-y-8"
  >
    <div className="text-center">
      <Brain className="w-16 h-16 text-indigo-500 mx-auto mb-4" />
      <h1 className="text-3xl font-bold text-gray-900 mb-2">AI-Powered Quizzes</h1>
      <p className="text-gray-600">Test your knowledge with personalized questions generated by Meta Llama-4</p>
    </div>
    <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
      {quizTopics.map((topic, index) => (
        <QuizTopicCard key={topic.id} topic={topic} onStartQuiz={onStartQuiz} index={index} />
      ))}
    </div>
    <div className="bg-gradient-to-r from-indigo-50 to-purple-50 rounded-xl p-8">
      <h2 className="text-2xl font-bold text-gray-900 mb-6 text-center">Quiz Features</h2>
      <div className="grid md:grid-cols-3 gap-6">
        <div className="text-center">
          <Zap className="w-8 h-8 text-indigo-500 mx-auto mb-3" />
          <h3 className="font-semibold text-gray-900 mb-2">AI-Generated</h3>
          <p className="text-sm text-gray-600">Questions based on your learning progress</p>
        </div>
        <div className="text-center">
          <Clock className="w-8 h-8 text-purple-500 mx-auto mb-3" />
          <h3 className="font-semibold text-gray-900 mb-2">Timed Challenges</h3>
          <p className="text-sm text-gray-600">Practice under time pressure to improve speed</p>
        </div>
        <div className="text-center">
          <Trophy className="w-8 h-8 text-yellow-500 mx-auto mb-3" />
          <h3 className="font-semibold text-gray-900 mb-2">Earn Points</h3>
          <p className="text-sm text-gray-600">Get points and achievements for completing quizzes</p>
        </div>
      </div>
    </div>
  </motion.div>
);

export default QuizTopicSelection;